<?php
/**
 * TL_ROOT/system/modules/html5media/languages/de/default.php 
 * 
 * TYPOlight extension: html5media 1.0.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : LGPL, GPL 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['movies'] = "Filme";
$GLOBALS['TL_LANG']['CTE']['html5']['0'] = "HTML 5 Film/Tondatei";
$GLOBALS['TL_LANG']['CTE']['html5']['1'] = "erzeugt HTML-Code, um mit HTML 5 eingebettete Filme oder Tondateien abzuspielen.";
 
?>
