<?php
/**
 * TL_ROOT/system/modules/html5media/languages/de/tl_content.php 
 * 
 * TYPOlight extension: html5media 1.0.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : LGPL, GPL 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['movie_width']['0'] = "Filmbreite";
$GLOBALS['TL_LANG']['tl_content']['movie_width']['1'] = "Geben Sie die Breite des Films an.";
$GLOBALS['TL_LANG']['tl_content']['movie_height']['0'] = "Filmhöhe";
$GLOBALS['TL_LANG']['tl_content']['movie_height']['1'] = "Geben Sie die Höhe des Films an.";
$GLOBALS['TL_LANG']['tl_content']['movie_preview']['0'] = "Filmvorschau für die Nicht-HTML 5 Alternative";
$GLOBALS['TL_LANG']['tl_content']['movie_preview']['1'] = "Bitte wählen Sie ein Bild aus, dass als Vorschau angezeigt wird, wenn kein HTML 5 verwendet wird.";
$GLOBALS['TL_LANG']['tl_content']['movie_webm']['0'] = "WebM Filmdatei";
$GLOBALS['TL_LANG']['tl_content']['movie_webm']['1'] = "Bitte wählen Sie eine WebM (WEBM) Filmdatei aus der Dateiverwaltung aus.";
$GLOBALS['TL_LANG']['tl_content']['movie_mp4']['0'] = "MP4 Filmdatei";
$GLOBALS['TL_LANG']['tl_content']['movie_mp4']['1'] = "Bitte wählen Sie eine H.264 (MP4) Filmdatei aus der Dateiverwaltung aus.";
$GLOBALS['TL_LANG']['tl_content']['movie_ogg']['0'] = "OGG Filmdatei";
$GLOBALS['TL_LANG']['tl_content']['movie_ogg']['1'] = "Bitte wählen Sie eine Theora (OGV) Filmdatei aus der Dateiverwaltung aus.";
$GLOBALS['TL_LANG']['tl_content']['audio_webm']['0'] = "WebM Audiodatei";
$GLOBALS['TL_LANG']['tl_content']['audio_webm']['1'] = "Bitte wählen Sie eine WebM Audio-Datei aus der Dateiverwaltung aus.";
$GLOBALS['TL_LANG']['tl_content']['audio_mp3']['0'] = "MP3 Audiodatei";
$GLOBALS['TL_LANG']['tl_content']['audio_mp3']['1'] = "Bitte wählen Sie eine MP3 Audio-Datei aus der Dateiverwaltung aus.";
$GLOBALS['TL_LANG']['tl_content']['audio_ogg']['0'] = "OGG Audiodatei";
$GLOBALS['TL_LANG']['tl_content']['audio_ogg']['1'] = "Bitte wählen Sie eine OGG Audio-Datei aus der Dateiverwaltung aus.";
$GLOBALS['TL_LANG']['tl_content']['movie_controls']['0'] = "Film-Steuerelemente anzeigen";
$GLOBALS['TL_LANG']['tl_content']['movie_controls']['1'] = "Wählen Sie aus, ob Steuerelemente zum Abspielen des Films angezeigt werden sollen.";
$GLOBALS['TL_LANG']['tl_content']['movie_preload']['0'] = "Film im Voraus laden";
$GLOBALS['TL_LANG']['tl_content']['movie_preload']['1'] = "Wählen Sie aus, ob der Film im Voraus geladen werden soll.";
$GLOBALS['TL_LANG']['tl_content']['movie_autoplay']['0'] = "Film automatisch abspielen";
$GLOBALS['TL_LANG']['tl_content']['movie_autoplay']['1'] = "Wählen Sie aus, ob der Film automatisch abgespielt werden soll.";
$GLOBALS['TL_LANG']['tl_content']['movie_loop']['0'] = "Film wiederholen";
$GLOBALS['TL_LANG']['tl_content']['movie_loop']['1'] = "Wählen Sie aus, ob der Film in einer Schleife wiederholt werden soll.";
$GLOBALS['TL_LANG']['tl_content']['audio_controls']['0'] = "Audio-Steuerelemente anzeigen";
$GLOBALS['TL_LANG']['tl_content']['audio_controls']['1'] = "Wählen Sie aus, ob Steuerelemente zum Abspielen der Audiodatei angezeigt werden sollen.";
$GLOBALS['TL_LANG']['tl_content']['audio_preload']['0'] = "Audiodatei im Voraus laden";
$GLOBALS['TL_LANG']['tl_content']['audio_preload']['1'] = "Wählen Sie aus, ob die Audiodatei im Voraus geladen werden soll.";
$GLOBALS['TL_LANG']['tl_content']['audio_autoplay']['0'] = "Audiodatei automatisch abspielen";
$GLOBALS['TL_LANG']['tl_content']['audio_autoplay']['1'] = "Wählen Sie aus, ob die Audiodatei automatisch abgespielt werden soll.";
$GLOBALS['TL_LANG']['tl_content']['audio_loop']['0'] = "Audiodatei wiederholen";
$GLOBALS['TL_LANG']['tl_content']['audio_loop']['1'] = "Wählen Sie aus, ob die Audiodatei in einer Schleife wiederholt werden soll.";
$GLOBALS['TL_LANG']['tl_content']['movie_legend'] = "Film-Einstellungen";
$GLOBALS['TL_LANG']['tl_content']['audio_legend'] = "Audio-Einstellungen";
 
?>
