<?php
/**
 * TL_ROOT/system/modules/html5media/languages/it/default.php 
 * 
 * Contao extension: html5media 1.0.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : LGPL, GPL 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Giulio Bettega (chalda) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['movies'] = "Elemento Video";
$GLOBALS['TL_LANG']['CTE']['html5']['0'] = "HTML5 video/audio";
$GLOBALS['TL_LANG']['CTE']['html5']['1'] = "genera  il codice HTML per visualizzare video e audio";
 
?>
