<?php
/**
 * TL_ROOT/system/modules/html5media/languages/it/tl_content.php 
 * 
 * Contao extension: html5media 1.0.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : LGPL, GPL 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Giulio Bettega (chalda) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['movie_width']['0'] = "Larghezza video";
$GLOBALS['TL_LANG']['tl_content']['movie_width']['1'] = "Inserisci la larghezza del video";
$GLOBALS['TL_LANG']['tl_content']['movie_height']['0'] = "Altezza video";
$GLOBALS['TL_LANG']['tl_content']['movie_height']['1'] = "Inserisci l'altezza del video";
$GLOBALS['TL_LANG']['tl_content']['movie_preview']['0'] = "Anteprima immagine";
$GLOBALS['TL_LANG']['tl_content']['movie_preview']['1'] = "Seleziona l'anteprima dell'immagine per la versione non HTML5";
$GLOBALS['TL_LANG']['tl_content']['movie_mp4']['0'] = "File video MP4";
$GLOBALS['TL_LANG']['tl_content']['movie_mp4']['1'] = "Seleziona un filmato H.264 (MP4) dalla directory";
$GLOBALS['TL_LANG']['tl_content']['movie_ogg']['0'] = "File video OGG";
$GLOBALS['TL_LANG']['tl_content']['movie_ogg']['1'] = "Seleziona un filmato Theora (OGV) dalla directory";
$GLOBALS['TL_LANG']['tl_content']['audio_mp3']['0'] = "File audio MP3";
$GLOBALS['TL_LANG']['tl_content']['audio_mp3']['1'] = "Seleziona un file audio MP3 dalla directory";
$GLOBALS['TL_LANG']['tl_content']['audio_ogg']['0'] = "File audio OGG";
$GLOBALS['TL_LANG']['tl_content']['audio_ogg']['1'] = "Seleziona un file audio OGG dalla directory";
$GLOBALS['TL_LANG']['tl_content']['movie_controls']['0'] = "Mostra i controlli video";
$GLOBALS['TL_LANG']['tl_content']['movie_controls']['1'] = "Selezionare per visualizzare i controlli video";
$GLOBALS['TL_LANG']['tl_content']['movie_preload']['0'] = "Pre-caricamento filmato";
$GLOBALS['TL_LANG']['tl_content']['movie_preload']['1'] = "Selezionare se il filmato deve essere pre-caricato";
$GLOBALS['TL_LANG']['tl_content']['movie_autoplay']['0'] = "Riproduzione automatica video";
$GLOBALS['TL_LANG']['tl_content']['movie_autoplay']['1'] = "Selezionare se il filmato deve partire automaticamente";
$GLOBALS['TL_LANG']['tl_content']['movie_loop']['0'] = "Filmato a ciclo continuo";
$GLOBALS['TL_LANG']['tl_content']['movie_loop']['1'] = "Selezionare se il filmato deve essere continuamente riprodotto";
$GLOBALS['TL_LANG']['tl_content']['audio_controls']['0'] = "Visualizza controlli audio";
$GLOBALS['TL_LANG']['tl_content']['audio_controls']['1'] = "Selezionare per visualizzare i controlli audio";
$GLOBALS['TL_LANG']['tl_content']['audio_preload']['0'] = "Pre-caricamento audio";
$GLOBALS['TL_LANG']['tl_content']['audio_preload']['1'] = "Selezionare se l'audio deve essere pre-caricato";
$GLOBALS['TL_LANG']['tl_content']['audio_autoplay']['0'] = "Riproduzione automatica audio";
$GLOBALS['TL_LANG']['tl_content']['audio_autoplay']['1'] = "Selezionare se l'audio deve partire automaticamente";
$GLOBALS['TL_LANG']['tl_content']['audio_loop']['0'] = "Audio a ciclo continuo";
$GLOBALS['TL_LANG']['tl_content']['audio_loop']['1'] = "Selezionare se l'audio deve essere continuamente riprodotto";
$GLOBALS['TL_LANG']['tl_content']['movie_legend'] = "Impostazioni del filmato";
$GLOBALS['TL_LANG']['tl_content']['audio_legend'] = "Impostazioni dell'audio";
 
?>
